# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            J. Andrew Rogers
tagline:          Pursuit of a Perfect Algorithm
url:              http://jandrewrogers.com
paginate:         1
baseurl:          /
author:
  name:           J. Andrew Rogers
  url:            https://twitter.com/jandrewrogers
  email:          andrew@jarbox.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
