# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            J. Andrew Rogers
tagline:          Pursuit of a Perfect Algorithm
url:              http://jandrewrogers.com
paginate:         1
baseurl:          /
author:
  name:           J. Andrew Rogers
  twitter:        https://twitter.com/jandrewrogers
  facebook:       https://www.facebook.com/j.andrew.rogers
  linkedin:       https://www.linkedin.com/in/jandrewrogers
  email:          andrew@jarbox.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Plugins
plugins: [jekyll-paginate]
